[package]
name = "timepulse2"
version = "0.1.0"
description = "A big, always-readable desktop clock, stopwatch and timer for Linux"
edition = "2021"

[lib]
name = "timepulse2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
